# Generated by Django 2.2.6 on 2019-12-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0042_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('discuss_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('like_num', models.IntegerField(default=0)),
                ('time', models.CharField(blank=True, max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Discuss')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
