# Generated by Django 2.2.6 on 2019-12-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='time',
        ),
    ]
