# Generated by Django 2.2.6 on 2019-12-12 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_discuss_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
