# Generated by Django 2.2.6 on 2019-11-25 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191125_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
