# Generated by Django 2.2.6 on 2019-11-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='用户',
        ),
    ]
