# Generated by Django 2.2.6 on 2019-11-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='usertype',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
