# Generated by Django 2.2.6 on 2019-11-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_admin_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='usertype',
            field=models.IntegerField(default=2, max_length=10),
        ),
    ]
