# Generated by Django 2.2.6 on 2019-12-02 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191202_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
