# Generated by Django 2.2.6 on 2019-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191204_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
