# Generated by Django 2.2.6 on 2019-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_activity_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
