# Generated by Django 2.2.6 on 2019-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_competition_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
