# Generated by Django 2.2.6 on 2019-12-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_act_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com_Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name': '比赛报名',
                'verbose_name_plural': '比赛报名',
            },
        ),
    ]
