# Generated by Django 2.2.6 on 2019-12-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_com_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='retake',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='elective',
            name='score',
            field=models.IntegerField(blank=True, default=80),
            preserve_default=False,
        ),
    ]
