# Generated by Django 2.2.6 on 2019-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191205_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='retake',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
