# Generated by Django 2.2.6 on 2019-12-05 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20191205_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='style',
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
