# Generated by Django 2.2.6 on 2019-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191205_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
