# Generated by Django 2.2.6 on 2019-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191205_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
