# Generated by Django 2.2.6 on 2019-12-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_exam_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
