# Generated by Django 2.2.6 on 2019-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20191205_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='retake',
            field=models.IntegerField(default=0),
        ),
    ]
