# Generated by Django 2.2.6 on 2019-12-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191206_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
