# Generated by Django 2.2.6 on 2019-12-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_student_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
