# Generated by Django 2.2.6 on 2019-12-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='cid',
        ),
    ]
