# Generated by Django 2.2.6 on 2019-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20191211_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
